name: School-iOS
options:
  developmentLanguage: ru
  knownRegions: ["ru"]
  useBaseInternationalization: false
  enableBaseInternationalization: false
attributes:
  ORGANIZATIONNAME: asigonin
configs:
  Debug: debug
  Internal: release
  Release: release
settings:
  base:
    VERSIONING_SYSTEM: apple-generic
    CURRENT_PROJECT_VERSION: 1
    SWIFT_VERSION: 5.8
    DEVELOPMENT_TEAM: RJZ3DQ7A56 
    CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER: YES
    CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: YES
    OTHER_LDFLAGS: 
      - -Objc
    ENABLE_BITCODE: NO
  configs:
    Debug:
      OTHER_SWIFT_FLAGS: -D DEBUG
    Internal:
      OTHER_SWIFT_FLAGS: -D INTERNAL
      SWIFT_COMPILATION_MODE: wholemodule
    Release:
      OTHER_SWIFT_FLAGS: -D RELEASE
      SWIFT_COMPILATION_MODE: wholemodule
targets:
  School:
    type: application
    platform: iOS
    deploymentTarget: 16.0
    info:
      path: School-iOS/Resources/Info.plist
      properties:
        NSAppClip:
          NSAppClipRequestEphemeralUserNotification: NO
          NSAppClipRequestLocationConfirmation: NO
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: YES
        UILaunchStoryboardName: Launch Screen
    scheme:
    dependencies:
      - package: KeychainAccess
      - package: Netfox
        product: netfox
      - package: Factory
 
      # - package: CoreNetworking
      # - package: CoreAssembly
      # - package: CoreStorage
      # - package: CoreNavigation      
      # - package: CoreServices

    sources:
      - path: School-iOS
    prebuildScripts:
      - script: |
            if [ "${FASTLANE_SCAN}" != "Running" ]; then
              if [ "${CONFIGURATION}" == "Debug" ]; then
                export PATH="$PATH:/opt/homebrew/bin"
                if which mint >/dev/null; then
                mint run swiftformat swiftformat School-iOS --quiet --conflictmarkers ignore
                fi
              fi
            fi
        name: SwiftFormat
    attributes:
      ProvisioningStyle: Manual
      DevelopmentTeam: RJZ3DQ7A56
    settings:
      base:
        TARGETED_DEVICE_FAMILY: "1"
        PRODUCT_BUNDLE_IDENTIFIER: ru.asigonin.school-ios
packages:
# Local

    # CoreAssembly:
    #     path: Packages/Core/CoreAssembly
    # CoreStorage:
    #     path: Packages/Core/CoreStorage
    # CoreNavigation:
    #     path: Packages/Core/CoreNavigation
    # CoreNetworking:
    #     path: Packages/Core/CoreNetworking
    # CoreServices:
    #     path: Packages/Core/CoreServices

# External
    Netfox:
        url: https://github.com/kasketis/netfox
        from: 1.20.0
    KeychainAccess:
        url: https://github.com/kishikawakatsumi/KeychainAccess
        from: 4.2.2
    Factory:
        url: https://github.com/hmlongco/Factory
        from: 2.2.0
